chat script takes stdin

diff --git a/chat b/chat
--- a/chat
+++ b/chat
@@ -9,21 +9,33 @@ CONTINUE=false
 
 while getopts ":3c" opt; do
   case $opt in
-    3)
-      MODEL="gpt-3.5-turbo"
-      ;;
-    c)
-      CONTINUE=true
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
+  3)
+    MODEL="gpt-3.5-turbo"
+    ;;
+  c)
+    CONTINUE=true
+    ;;
+  \?)
+    echo "Invalid option: -$OPTARG" >&2
+    exit 1
+    ;;
   esac
 done
-shift $((OPTIND -1))
+shift $((OPTIND - 1))
+
+# append stdin to USER_MESSAGE
+if [ ! -t 0 ]; then
+  STDIN_MESSAGE=$(cat -)
+else
+  STDIN_MESSAGE=""
+fi
 
 USER_MESSAGE="$*"
+
+# append a few empty lines to USER_MESSAGE
+USER_MESSAGE="$USER_MESSAGE\n\n\n"
+
+USER_MESSAGE="$USER_MESSAGE $STDIN_MESSAGE"
 
 if $CONTINUE && [ -s "$CHAT_FILE" ]; then
   OLD_CONVERSATION_JSON=$(<"$CHAT_FILE")
@@ -33,7 +45,7 @@ fi
 
 OLD_CONVERSATION_JSON=$(echo "$OLD_CONVERSATION_JSON" | jq --arg msg "$USER_MESSAGE" '. + [{"role": "user", "content": $msg}]')
 
-read -r -d '' PAYLOAD <<- EOM
+read -r -d '' PAYLOAD <<-EOM
 {
    "model": "$MODEL",
    "messages": $OLD_CONVERSATION_JSON
@@ -46,6 +58,6 @@ RESPONSE=$(curl -sS "$API_URL" \
   --data "$PAYLOAD")
 
 ASSISTANT_MESSAGE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
-echo "$OLD_CONVERSATION_JSON" | jq --arg msg "$ASSISTANT_MESSAGE" '. + [{"role": "assistant", "content": $msg}]' > "$CHAT_FILE"
+echo "$OLD_CONVERSATION_JSON" | jq --arg msg "$ASSISTANT_MESSAGE" '. + [{"role": "assistant", "content": $msg}]' >"$CHAT_FILE"
 
 echo "$RESPONSE" | jq -r '(.choices[0].message.content,.error.message)//empty'
